export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_PICTURES_PENDING = 'REQUEST_PICTURESS_PENDING';
export const REQUEST_PICTURES_SUCCESS = 'REQUEST_PICTURES_SUCCESS';
export const REQUEST_PICTURES_FAILED = 'REQUEST_PICTURES_FAILED';

export const REQUEST_FAVORITES_SUCCESS = 'REQUEST_FAVORITES_SUCCESS';
export const REQUEST_FAVORITES_EMPTY = 'REQUEST_FAVORITES_EMPTY';

export const FAVORITES_PAGE = 'FAVORITES_PAGE';
export const HOME_PAGE = 'HOME_PAGE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const SHOW_CONFIRMATION = 'SHOW_CONFIRMATION';